### ISSUE TITLE
v_eval missing "valid" argument + typo fix

### ISSUE THREAD

**Issue by abenbihi** [ChanhyukYun/invSfM_torch#1]
Hi,

Thank you so much for writing this code and releasing it, this is extremely useful.
The original invsfm is great but getting tensorflow 1.10 to run on modern machine can be tricky.

This issue reports a small typo in the main code that complains about `valid` not being defined in `v_eval` in torch_invsfm.py.
Adding `valid` as an argument solves the issue i.e. 
- replacing  `def v_eval(inp_ch, vinp, vwts_dir)` with `def v_eval(inp_ch, vinp, vwts_dir, valid)`
- replacing `v_eval(inp_ch, vinp, vnet_wts_fp)` with `v_eval(inp_ch, vinp, vnet_wts_fp, valid)`

Best,

**Comment by ChanhyukYun** [comment]
Hi,

Thanks for letting me know.
You're right, there should be valid as an input for v_eval.

I think it was a mix-up when cleaning the codes.
The code is fixed now.
